config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :validate_twitters
  resources :transactions
  resources :credits
  resources :validate_facebooks
  resources :validate_instagrams
    get '/set_likes/:id', to: 'validate_facebooks#set_likes'
    get '/get_likes/:id', to: 'validate_facebooks#get_likes'
    get '/set_instagram/:id', to: 'validate_instagrams#set_instagram'
    get '/get_instagram/:id', to: 'validate_instagrams#get_instagram'
    get '/set_twitter/:id', to: 'validate_twitters#set_twitter'
    get '/get_twitter/:id', to: 'validate_twitters#get_twitter'
    get '/pull_new_product/:id', to: 'play#pull_new_product'
    get '/dashboard', to: 'dashboard#index'
    get '/hide/:id', to: 'dashboard#hide'
    get '/unhide/:id', to: 'dashboard#unhide'
    get '/verify', to: 'verify#index'
   get '/verify/:id', to: 'verify#verify'
      get '/skip/:id', to: 'skip#index'

      get '/new', to: 'products#new'

#Stripe
    get '/payola/confirm/:id', to: redirect('/success/%{id}')
    get '/success/:id', to: 'charges#make_charge'
        get '/success', to: 'charges#index'
        get '/charges', to: redirect('/success')

  resources :charges

#For a user's viewing pleasure lol:
    get '/trial', to: 'validate_facebooks#trial'
    get 'play', to: 'play#product'

    get '/my_products', to: 'user_created_products#index'
  resources :products
    get 'sourc', to: 'products#index'
    get 'new_link', to: 'products#new'
    root to: 'play#product'

  mount Payola::Engine => '/payola', as: :payola

end

app/controllers/play_controller.rb
class PlayController < ApplicationController





   def product
      @products_all = Product.where("owner_uid = #{current_user.id}")
      #for header balance

      @products_liked_by_user = Transaction.where("recipient_uid = #{current_user.id} OR sender_uid = #{current_user.id}")
      product_skips = Skip.where("uid = #{current_user.id}")
      count = 0
      @product_ids = []
      @products_liked_by_user.each do |x|
         unless(x.product_id.blank?)
            @product_ids[count] = x.product_id
            count += 1
         end
      end
      product_skips.each do |x|
         unless(x.product_id.blank?)
            @product_ids[count] = x.product_id
            count += 1
         end
      end
      @current_user_identity = Identity.where("user_id = #{current_user.id} AND provider = 'facebook'").first()


      # PRICE NEEDS TO BE > BALANCE of OWNER
      #
      #
      #


      if(@product_ids == []) #ensure we are not checking an empty array, as that would yield an unexpected result
         @product_ids[0] = 0
      end
      if(params[:id].blank?)
         @products = Product.where.not("id IN (?) OR owner_uid = (?)", @product_ids, current_user.id).where("is_active = 1").order("price DESC")
         get_affordable_product()
      else

         @products = Product.where.not("id IN (?) OR owner_uid = (?)", @product_ids, current_user.id).where("provider = (?) AND is_active = 1 ", params[:id]).order("price DESC")
         get_affordable_product()
      end
   end


   def pull_new_product

      #for header balance

      @products_liked_by_user = Transaction.where("recipient_uid = #{current_user.id} OR sender_uid = #{current_user.id}")

      product_skips = Skip.where("uid = #{current_user.id}")
      count = 0
      @product_ids = []

      @products_liked_by_user.each do |x|
         unless(x.product_id.blank?)
            @product_ids[count] = x.product_id

            count += 1
         end

      end
      product_skips.each do |x|
         unless(x.product_id.blank?)
            @product_ids[count] = x.product_id
            count += 1
         end
      end
      if(@product_ids == []) #ensure we are not checking an empty array, as that would yield an unexpected result
         @product_ids[0] = 0
      end
      # @product = Product.where("price < #{@Balance}").where.not("id IN (?)", @product_ids).first
      if(params[:id] == "null")
         @products = Product.where.not("id IN (?) OR owner_uid = (?)", @product_ids, current_user.id).where("is_active = 1").order("price DESC")
       get_affordable_product()
      else
         @products = Product.where.not("id IN (?) OR owner_uid = (?)", @product_ids, current_user.id).where("provider = (?) AND is_active = 1 ", params[:id]).order("price DESC")
       get_affordable_product()
      end

      respond_to do |format|
         format.json { render json: @product }
      end
   end


   def get_affordable_product
      temp_index = 0;
      continue = true
      while(continue)
            begin
         @temp_product = @products[temp_index]

            @balance_of_user = Credit.find_by_uid(@temp_product.owner_uid)
            if @balance_of_user.balance >= @temp_product.price
               @product = @temp_product
               continue = false
            end
         rescue
            continue = false
         end
         temp_index += 1
      end
   end

   def index

   end


end

app/helpers/play_helper.rb
module PlayHelper
end

app/views/play/index.html.erb
<p id="notice"><%= notice %></p>

<p>    <%= link_to 'Facebook', controller: "play", id: "facebook" %></p>

<p>    <%= link_to 'Twitter', controller: "play", id: "twitter" %></p>

<p>    <%= link_to 'Instagram', controller: "play", id: "instagram" %></p>

app/views/play/product.html.erb
<a href="/play">All</a> |
<a href="/play?id=facebook">Facebook</a> |
<a href="/play?id=instagram">Instagram</a> |
<a href="/play?id=twitter">Twitter</a>

<p id="notice"><%= notice %></p>

<%
last_hidden_index = 0 #instantiate
last_show_index = 0
if (!@product.nil?) %>
<script type="text/javascript">

var windows = {};
windows['window_one'] = false;
windows['window_two'] = false;
windows['window_three'] = false;

$(document).on( "click", "#window_button",function() {
   console.log('in click');

   open_window(this,'<%= @product.pretty_url %>', '<%= @product.id %>','<%= @product.provider %>');

});
$(document).on( "click", "#skip",function() {
   url = "/skip/<%= @product.id %>.json"
   $.get(url,function(skip_return,status) {
      console.log(skip_return)
      get_next(provider)
   });
});

function get_next(provider){
   console.log('in get next');
   // $("#container").css({display: "none"});
   // $("#loading").css({display: "block"});

$('#container').addClass('animated bounceOutLeft');
   <% if params[:id].nil?  %>

   var next_provider = null;
   <% else %>
   var next_provider = '<%= params[:id] %>';
   <% end %>
   console.log(next_provider)
   var url = 'http://localhost:3000/pull_new_product/'+ next_provider+'.json';
   console.log(url);
   $.get(url,function(new_product,status) {
      console.log(new_product);
      //handle null case bro
      if(new_product != null){
         // reloadLikeButton(new_product.url);
         console.log(new_product.url);
         console.log('in NOT NULL')
         // $("#id").text( new_product.id);
         $("#name").text(new_product.name);
         $("#provider").text(new_product.provider);
         $("#price").text(new_product.price);
         if(new_product.provider == "twitter" || new_product.provider == "instagram"){
            var verb = "Follow ";
         }else if (new_product.provider == "facebook") {
            var verb = "Like ";
         }
         $("#window_button").text(verb + new_product.name);
         $('#cover_photo').attr('src',new_product.cover_photo);
         $('#profile_pic').attr('src',new_product.profile_pic);
         $('#container').removeClass('animated bounceOutLeft');
         $('#container').addClass('animated bounceInLeft');
         $(document).off('click','#window_button');
         $(document).on( "click", "#window_button",function() {
            console.log('update on window button click');
            open_window(this,new_product.pretty_url, new_product.id,provider)

         });
         $(document).off('click','#skip');
         $(document).on( "click", "#skip",function() {
            console.log('update on skip button click');
            url = "/skip/"+new_product.id+".json"
            $.get(url,function(skip_return,status) {
               console.log(skip_return)
               get_next(provider)
            });
         });

      }else{
            $('#container').removeClass('animated bounceOutLeft');
            $('#container').addClass('animated bounceInLeft');
         document.getElementById('container').innerHTML = "NO PRODUCTS LEFT BRO";

      }
      $("#container").css({display: "block"});
      $("#loading").css({display: "none"});
   });
}

var data_parse;
function open_window(element, url, id, provider){
   console.log(provider)
   if(provider == "facebook"){
      if(id == null){
         set_url = 'http://localhost:3000/set_likes/<%= @product.id %>.json';
      }else{
         set_url = 'http://localhost:3000/set_likes/'+id+'.json';
      }
   }else if (provider == "twitter") {
      if(id == null){
         set_url = 'http://localhost:3000/set_twitter/<%= @product.id %>.json';
      }else{
         set_url = 'http://localhost:3000/set_twitter/'+id+'.json';
      }
   }else if (provider == "instagram") {
      if(id == null){
         set_url = 'http://localhost:3000/set_instagram/<%= @product.id %>.json';
      }else{
         set_url = 'http://localhost:3000/set_instagram/'+id+'.json';
      }
   }

   var window_one = window.open(url,"window_one","width=800,height=400,scrollbars=no");
   console.log('window opened');

   $.get(set_url,function(data,status) {
      console.log(data);
      data_parse = JSON.parse(data);
      data_get_id = data_parse['id'];
      console.log("Data ID: " + data_get_id);
      check_if_closed();
   },'html');

   console.log('Ajax ran');
   console.log("Facebook window is opened: " + window_one.closed);
   counter = 0;

   function check_if_closed() {
      setTimeout(function(){
         console.log('in check if closed');
         if(window_one.closed){
            console.log('Closed via user');
            clearTimeout(automated_close); clearTimeout(check_if_closed); //Stop timing
            console.log('Closed out check and automated');
            check_if_user_liked(data_get_id);
         }else{
            if(counter == 0){
               automated_close();
               counter += 1;
            }
            check_if_closed();
         }
      }, 1000);
   }

   function automated_close() {
      setTimeout(function(){
         if(!window_one.closed){
            window.open('', '_self', ''); window_one.close(); //Both for closing the window
            console.log('Closed via code');
            clearTimeout(automated_close); clearTimeout(check_if_closed); //Stop timing
         }
      }, 15000);
   }

   function check_if_user_liked(data_get_id){
      if(provider == "facebook"){
         get_url = 'http://localhost:3000/get_likes/'+ data_get_id + '.json';
      }else if (provider == "twitter") {
         get_url = 'http://localhost:3000/get_twitter/'+ data_get_id + '.json'
      }else if (provider == "instagram") {
         get_url = 'http://localhost:3000/get_instagram/'+ data_get_id + '.json';
      }
      $.get(get_url,function(data,status) {
         data_parse = JSON.parse(data);
         awarded = data_parse.awarded;
         if (awarded == 1){
            console.log('awarded');
            console.log('new balance is: ' + data_parse.balance)
            $("#balance").text(data_parse.balance);
            get_next(provider);
         }else{
            console.log('not awarded');
            get_next(provider);
         }
      },'html');
   }
}

$(document).on("click", ".hide", function(){
   console.log('here');
   var id = $(this).data('id');
   var index = $(this).data('index');
   console.log(id);

   url = "/hide/"+id+".json";
   $.get(url, function(data){
      console.log(data);
      $('*[data-show='+id+']').css({ "display": "none"});
      $('*[data-hide='+id+']').css({ "display": "block"});
   });
});

$(document).on("click", ".unhide", function(){
   console.log('here');
   var id = $(this).data('id');
   console.log(id);
   url = "/unhide/"+id+".json";
   $.get(url, function(data){
      console.log(data);
      $('*[data-show='+id+']').css({ "display": "block"});
      $('*[data-hide='+id+']').css({ "display": "none"});
   });
});

</script>

<div id="container" style="display:block;float:left">

<!-- <button id="start">Start</button>
<div id="timer">15 seconds left
</div> -->

<p>
<strong>Name:</strong>
<span id="name"> <%= @product.name %></span>

</p>

<p>
<strong>Price:</strong>
<span id="price"> <%= @product.price %></span>

</p>
<p>
<strong>Provider:</strong>
<span id="provider"><%= @product.provider %></span>
</p>


<p>
<img id="cover_photo" src="<%= @product.cover_photo %>" style="width:200px;">
<img id="profile_pic" src="<%= @product.profile_pic %>" style="width:50px;">
</p>

<p>
<strong>URL:</strong>

<button id="window_button">
<%   if(@product.provider == "twitter" || @product.provider == "instagram")
verb = "Follow ";
elsif (@product.provider == "facebook")
verb = "Like ";
end %>
<%= verb + @product.name %></button>
<button id="skip">SKIP</button>
</p>
</div>


   <div id="loading" style="display:none">
      <%= image_tag "giphy.gif" %>
   </div>
      <% else %>
      NOTHING LEFT BRO<br>
   <% end %>
         <%= link_to 'Back', products_path %>
<!-- FOOTER -->


<div id="sidebar">
   <table style="position:relative;margin:0 auto;" id="hideshow">
      <tbody>

         <%
         index = 1 #skip the Active row
          counter = 0
         neither = true %>
         <% @products_all.each do |product| %>
         <% if counter == 0 %>
         <tr>
            <td colspan="5" style="text-align:center">
               ACTIVE
            </td>
         </tr>
         <%
         counter += 1
         neither = false %>
         <% end %>
         <% if product.is_active == 1 %>
            <tr style="display:block"  data-show="<%= product.id %>">
         <% else %>
            <tr style="display:none" data-show="<%= product.id %>">
         <% end %>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= link_to product.url, product %></td>
            <td><%= link_to 'More', product %></td>
            <td><button class="hide" data-index="<%= index %>" data-id="<%= product.id %>">HIDE</button></td>
         </tr>

         <% end %>

         <% counter = 0 %>
         <% @products_all.each do |product| %>
         <% if counter == 0 %>
         <tr>
            <td colspan="5" style="text-align:center">
               HIDDEN
            </td>
         </tr>
         <%
         index += 1 #skip the Hidden row
         counter += 1
         neither = false%>
         <% end %>
         <% if product.is_active == 0 %>
         <tr style="display:block"  data-hide="<%= product.id %>">
      <% else %>
         <tr style="display:none"  data-hide="<%= product.id %>">
      <% end %>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= link_to product.url, product %></td>
            <td><%= link_to 'More', product %></td>
            <!-- <td><%= link_to 'Edit', edit_product_path(product) %></td> -->
               <td><button class="unhide" data-index="<%= index %>" data-hide="<%= product.id %>" data-id="<%= product.id %>">SHOW</button></td>
         </tr>
         <% end %>
         <% if neither %>
         <tr>
            <td colspan="6" style="text-align:center">
               <%= link_to 'Yo bro, you have no products, get on that!', new_product_path %>
            </td>
         </tr>
         <% end %>
      </tbody>
   </table>
</div>