config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :validate_twitters
  resources :transactions
  resources :credits
  resources :validate_facebooks
  resources :validate_instagrams
    get '/set_likes/:id', to: 'validate_facebooks#set_likes'
    get '/get_likes/:id', to: 'validate_facebooks#get_likes'
    get '/set_instagram/:id', to: 'validate_instagrams#set_instagram'
    get '/get_instagram/:id', to: 'validate_instagrams#get_instagram'
    get '/set_twitter/:id', to: 'validate_twitters#set_twitter'
    get '/get_twitter/:id', to: 'validate_twitters#get_twitter'
    get '/pull_new_product/:id', to: 'play#pull_new_product'
    get '/dashboard', to: 'dashboard#index'
    get '/hide/:id', to: 'dashboard#hide'
    get '/unhide/:id', to: 'dashboard#unhide'
    get '/verify', to: 'verify#index'
   get '/verify/:id', to: 'verify#verify'
      get '/skip/:id', to: 'skip#index'

      get '/new', to: 'products#new'

#Stripe
    get '/payola/confirm/:id', to: redirect('/success/%{id}')
    get '/success/:id', to: 'charges#make_charge'
        get '/success', to: 'charges#index'
        get '/charges', to: redirect('/success')

  resources :charges

#For a user's viewing pleasure lol:
    get '/trial', to: 'validate_facebooks#trial'
    get 'play', to: 'play#product'

    get '/my_products', to: 'user_created_products#index'
  resources :products
    get 'sourc', to: 'products#index'
    get 'new_link', to: 'products#new'
    root to: 'play#product'

  mount Payola::Engine => '/payola', as: :payola

end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
     abort('here')
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update

    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:uid, :balance)
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br>
    <%= f.number_field :uid %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.number_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credits</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.uid %></td>
        <td><%= credit.balance %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @credit.uid %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @credit.balance %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>