config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :validate_twitters
  resources :transactions
  resources :credits
  resources :validate_facebooks
  resources :validate_instagrams
    get '/set_likes/:id', to: 'validate_facebooks#set_likes'
    get '/get_likes/:id', to: 'validate_facebooks#get_likes'
    get '/set_instagram/:id', to: 'validate_instagrams#set_instagram'
    get '/get_instagram/:id', to: 'validate_instagrams#get_instagram'
    get '/set_twitter/:id', to: 'validate_twitters#set_twitter'
    get '/get_twitter/:id', to: 'validate_twitters#get_twitter'
    get '/pull_new_product/:id', to: 'play#pull_new_product'
    get '/dashboard', to: 'dashboard#index'
    get '/hide/:id', to: 'dashboard#hide'
    get '/unhide/:id', to: 'dashboard#unhide'
    get '/verify', to: 'verify#index'
   get '/verify/:id', to: 'verify#verify'
      get '/skip/:id', to: 'skip#index'

      get '/new', to: 'products#new'

#Stripe
    get '/payola/confirm/:id', to: redirect('/success/%{id}')
    get '/success/:id', to: 'charges#make_charge'
        get '/success', to: 'charges#index'
        get '/charges', to: redirect('/success')

  resources :charges

#For a user's viewing pleasure lol:
    get '/trial', to: 'validate_facebooks#trial'
    get 'play', to: 'play#product'

    get '/my_products', to: 'user_created_products#index'
  resources :products
    get 'sourc', to: 'products#index'
    get 'new_link', to: 'products#new'
    root to: 'play#product'

  mount Payola::Engine => '/payola', as: :payola

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create

    @transaction = Transaction.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:sender_uid, :recipient_uid, :payment_amount, :date_occured, :provider_type, :product_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_uid %><br>
    <%= f.number_field :sender_uid %>
  </div>
  <div class="field">
    <%= f.label :recipient_uid %><br>
    <%= f.number_field :recipient_uid %>
  </div>
  <div class="field">
    <%= f.label :payment_amount %><br>
    <%= f.number_field :payment_amount %>
  </div>
  <div class="field">
    <%= f.label :date_occured %><br>
    <%= f.datetime_select :date_occured %>
  </div>
  <div class="field">
    <%= f.label :provider_type %><br>
    <%= f.text_field :provider_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Sender uid</th>
      <th>Recipient uid</th>
      <th>Payment amount</th>
      <th>Date occured</th>
      <th>Provider type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.sender_uid %></td>
        <td><%= transaction.recipient_uid %></td>
        <td><%= transaction.payment_amount %></td>
        <td><%= transaction.date_occured %></td>
        <td><%= transaction.provider_type %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender uid:</strong>
  <%= @transaction.sender_uid %>
</p>

<p>
  <strong>Recipient uid:</strong>
  <%= @transaction.recipient_uid %>
</p>

<p>
  <strong>Payment amount:</strong>
  <%= @transaction.payment_amount %>
</p>

<p>
  <strong>Date occured:</strong>
  <%= @transaction.date_occured %>
</p>

<p>
  <strong>Provider type:</strong>
  <%= @transaction.provider_type %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>